version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.2

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          source_dir: src
          filters: *filters
      - orb-tools/pack:
          source_dir: src
          filters: *filters
      - orb-tools/review:
          source_dir: src
          filters: *filters
          exclude: RC009
      - shellcheck/check:
          filters: *filters
      - orb-tools/continue:
          orb_name: evals
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
          filters: *filters
